WARNING | 19:29:31 | web_data | Error in the data
Traceback (most recent call last):
  File "/home/iatmos/PycharmProjects/mod7.1/app.py", line 29, in data_processing
    data_pars(numbers)
  File "/home/iatmos/PycharmProjects/mod7.1/app.py", line 42, in data_pars
    return list(map(float, numbers.split('/')))
ValueError: could not convert string to float: '3 3'
WARNING | 19:44:50 | web_data | Error in the data
Traceback (most recent call last):
  File "/home/iatmos/PycharmProjects/mod7.1/app.py", line 29, in data_processing
    data_pars(numbers)
  File "/home/iatmos/PycharmProjects/mod7.1/app.py", line 42, in data_pars
    return list(map(float, numbers.split('/')))
ValueError: could not convert string to float: '23 h'
